### ISSUE TITLE
Watch Compatibility

### ISSUE THREAD

**Issue by ABianchini** [snietfeld/OpenChronograph#3]
What determines if a watch would be compatible with this board? Would this one work: [FTW1150](https://www.fossil.com/en-us/products/hybrid-smartwatch-commuter-dark-brown-leather/FTW1150.html)

**Comment by snietfeld** [comment]
I'm 95% sure the watch you listed would be fine, but I haven't tested that specific model so I can't say for certain. I can say that the Fossil Q Activist and Fossil Q Men's Machine are both compatible, and this watch looks like it's from the same family. I also can't say whether this watch uses a thin battery or the higher-capacity CR2430 (highly recommend watches designed for the CR2430).

The good news is that you won't have to void the warranty to find out if it's compatible. If you open the back up and pull the battery out, you'll be able to see pretty clearly if it's using the Soprod board and motors.

You might also join our Discord channel for more discussion here: https://discord.gg/hkmDgSk

**Comment by ABianchini** [comment]
Thank you very much!
